// again/框架/vue/project/foodpro/cookbook/src/views/FoodDetail.vue
<template>
  <div>
    <h1 v-for="item in resultList" :key="item.id">
      {{ item.name }}

      <p><img :src="item.pic" /></p>
      <h2>介绍：</h2>
      <p class="content" v-html="item.content"></p>
      <h2>材料：</h2>
      <p class="content" v-for="(m, index) in item.material" :key="m.mname">
        {{ index + 1 }}.{{ m.mname }}:{{ m.amount }}
      </p>
      <h2>步骤：</h2>
      <p
        class="content"
        v-for="(m, index) in item.process"
        :key="index"
        v-html="index + 1 + '.' + m.pcontent"
      ></p>
    </h1>
  </div>
</template>

<script>
import { Message } from "element-ui";
export default {
  data() {
    return {
      resultList: [],
    };
  },
  created() {
    this.diet();
  },
  methods: {
    diet() {
      if (this.$route.query.keyword != undefined) {
        this.$axios({
          method: "get",
          url: "/api/search",
          params: {
            keyword: this.$route.query.keyword,
            num: 10,
            appkey: "c671a4c29ec3381b",
          },
        }).then((res) => {
          if (res.data.result == "") {
            Message({ type: "error", message: "没有这道菜" });
            this.$router.push("/");
          } else {
            this.resultList = res.data.result.list;
          }
        });
      } else {
        this.$axios({
          url: "/api/byclass",
          method: "get",
          params: {
            classid: this.$route.query.classid,
            num: 10,
            start: 0,
            appkey: "c671a4c29ec3381b",
          },
        }).then((res) => {
          this.resultList = res.data.result.list;
        });
      }
    },
  },
};
</script>

<style scoped>
.content {
  font-size: 18px;
  font-style: normal;
  font-weight: 200;
}
</style>

// react/project/menu/src/FoodDetail.jsx
import axios from 'axios'
import React, { Component } from 'react'

export default class FoodDetail extends Component {
    state = {
        categoryId: "",
        resultList: [],
        keyword: ""
    }
    componentDidMount() {
        console.log(this.props);
        if (this.props.location.search.split("=")[1]) {
            this.getCategory()
        } else {
            this.getFood()
        }
    }
    getFood = () => {
        axios.get("http://localhost:3001/search", {
            params: {
                keyword: this.props.history.location.state.keyword,
                num: 10,
                appkey: "c671a4c29ec3381b"
            }
        }).then((res) => { this.setState({ resultList: res.data.result.list }) })
    }

    getCategory() {
        axios.get("http://localhost:3001/byclass", {
            params: {
                classid: this.props.history.location.search.split("=")[1],
                num: 10,
                start: 0,
                appkey: "c671a4c29ec3381b"
            }
        }).then((res) => { this.setState({ resultList: res.data.result.list }) })
    }
    render() {
        const list = this.state.resultList.map((item) => (<div>
            <h1 key={item.id}>{item.name}</h1>
            {/* <img src={item.pic}/> */}
            <h2>介绍：</h2>
            <p>{item.content}</p>
            <h2>材料：</h2>
            <p>{item.material.map((m, index) => <p key={index}>{index + 1}.{m.mname}:{m.amount}</p>)}</p>
            <h2>步骤：</h2>
            <p>{item.process.map((m, index) => <p key={index}>{index + 1}.{m.pcontent}</p>)}</p>
        </div>))
        return (
            <div>
                <h1 style={{textAlign:"center",color:"red"}}>FoodDetail 详情页面</h1>
                <div>{list}</div>
            </div>
        )
    }
}
