// vue/clitest/menu/src/views/MyHome.vue
<template>
    <div>
        <input type="text" v-model="searchValue" @keyup.enter="search">
        <div class="tags" v-for="(item,index) in tagList" :key="item.classid" @click="select(index)">{{item.name}}</div>
        <div class="type" v-for="item in typeList" :key="item.name" @click="detail(item.classid)">{{item.name}}</div>
    </div>
</template>

<script>
    export default {
        data(){
            return {
                searchValue:"",
                tagList:[],
                typeList:[]
            }
        },
        created(){
            console.log(this.recommend());
        },
        methods:{
            search(){
                this.$router.push(`/detail?keyword=${this.searchValue}`);
                
            },
            recommend(){
                this.$axios({
                    url:"/api/class",
                    method:"get",
                    params:{
                        appkey:"c671a4c29ec3381b"
                    }

                }).then(res=>{this.tagList = res.data.result;
                        this.typeList = this.tagList[0].list.splice(0,10);
                        });
            },
            select(index){
                this.typeList = this.tagList[index].list.splice(0,10);

            },
            detail(classid){
                this.$router.push(`/detail?classid=${classid}`);
            }

        }
    }
</script>

<style scoped>
input{width: 90%;margin-left: 5%;margin-top: 20px;}
.tags{display: inline-block;background-color: aquamarine;padding: 10px 10px;margin-left: 5px;margin-top: 5px;margin-bottom: 20px;}
.type{display: inline-block;background-color: wheat;padding: 30px 30px;margin-left: 10px;margin-top: 15px;margin-bottom: 20px;}
</style>

// react/project/menu/src/MyHome.jsx
import React, { Component } from 'react'
import axios from "axios"
export default class MyHome extends Component {
  state = {
    value: "",
    tagList: [],
    typeList: []
  }
  // keys = () => { this.props.history.push(`/detail?keyword=${this.state.value}`); }
  keys = () => { this.props.history.push({pathname:"/detail",state:{keyword:this.state.value}}); }
  handleInput = (e) => { this.setState({ value: e.target.value }); }
  search = () => {
    axios.get("http://localhost:3001/class", {
      params: {
        appkey: "c671a4c29ec3381b"
      }
    }).then((res) => { console.log(res); })
  }
  recommend = () => {
    axios.get("http://localhost:3001/class", {
      params: {
        appkey: "c671a4c29ec3381b"
      }
    }).then((res) => {
      this.setState({ tagList: res.data.result }, () => {
        console.log(1, this.state.tagList[0]);
        this.setState({ typeList: this.state.tagList[0].list.splice(0, 10) }, () => {
          console.log(2, this.state.typeList);
        })
      })
    })

  }
  // 选择大的类别
  select = (index) => {
    this.setState({ typeList: this.state.tagList[index].list.splice(0, 10) })
  }
  // 选择具体的小类别
  choose = (index) => {
   // 跳转到详情页面
    this.props.history.push(`/detail?classid=${index}`)
  }
  componentDidMount() {
    this.recommend()
  }
  render() {
    const list = this.state.tagList.map((item,index) => <span style={{ display: "inline-block", width: "80px", marginRight: "20px", background: "cyan", marginBottom: "20px", textAlign: "center" }} key={item.classid} onClick={()=>{this.select(index)}}>{item.name}</span>)
    const kind = this.state.typeList.map((item)=><span style={{ display: "inline-block", width: "80px", marginRight: "20px", background: "grey", marginBottom: "20px", textAlign: "center" }} key={item.classid} onClick={()=>{this.choose(item.classid)}}>{item.name}</span>)
    return (
      <div>
        <input type="text" value={this.state.value} onChange={this.handleInput} />
        <button onClick={this.keys}>搜索</button>
        <div>{list}</div>
        <div>{kind}</div>
      </div>
    )
  }
}
