// vue/clitest/menu/src/views/MyHome.vue
<template>
    <div>
        <input type="text" v-model="searchValue" @keyup.enter="search">
        <div class="tags" v-for="(item,index) in tagList" :key="item.classid" @click="select(index)">{{item.name}}</div>
        <div class="type" v-for="item in typeList" :key="item.name" @click="detail(item.classid)">{{item.name}}</div>
    </div>
</template>

<script>
    export default {
        data(){
            return {
                searchValue:"",
                tagList:[],
                typeList:[]
            }
        },
        created(){
            console.log(this.recommend());
        },
        methods:{
            search(){
                this.$router.push(`/detail?keyword=${this.searchValue}`);
                
            },
            recommend(){
                this.$axios({
                    url:"/api/class",
                    method:"get",
                    params:{
                        appkey:"c671a4c29ec3381b"
                    }

                }).then(res=>{this.tagList = res.data.result;
                        this.typeList = this.tagList[0].list.splice(0,10);
                        });
            },
            select(index){
                this.typeList = this.tagList[index].list.splice(0,10);

            },
            detail(classid){
                this.$router.push(`/detail?classid=${classid}`);
            }

        }
    }
</script>

<style scoped>
input{width: 90%;margin-left: 5%;margin-top: 20px;}
.tags{display: inline-block;background-color: aquamarine;padding: 10px 10px;margin-left: 5px;margin-top: 5px;margin-bottom: 20px;}
.type{display: inline-block;background-color: wheat;padding: 30px 30px;margin-left: 10px;margin-top: 15px;margin-bottom: 20px;}
</style>

// react/project/menu1/src/MyHome.jsx
import React, { useState, useEffect } from 'react'
import axios from 'axios'

export default function MyHome() {

    const [searchText, setSearchText] = useState("")
    const [list, setList] = useState([])
    const [kind, setKind] = useState([])

    useEffect(() => {
        axios.get("http://localhost:3001/class",
            {
                params: {
                appkey: "c671a4c29ec3381b"
                }
            }).then((res) => {
                let result = res.data.result
                console.log(res);
                // setList(result)

                // setKind(result[10].list.slice(0, 10))

            })
    })

    let search = () => {
        console.log(searchText);
    }

    let handleList = (i) => {
        console.log(i);
    }

    let handleKind = (i) => {
        console.log(i);
    }
    return (
        <div>
            <input type="text" placeholder='请输入想吃的菜' value={searchText} onChange={(e) => { setSearchText(e.target.value) }} />
            <button onClick={search}>搜索</button>
            <div >{list.map((item, index) => <li key={index} onClick={(index) => { handleList(index) }} style={{ listStyle: "none", background: "cyan", display: "inline-block", marginRight: "20px" }}>{item.name}</li>)}</div>
            <div>{kind.map((item, index) => <li key={index} onClick={(index) => { handleKind(index) }} style={{ listStyle: "none", background: "yellowGreen", display: "inline-block", marginRight: "20px", marginTop: "20px" }}>{item.name}</li>)}</div>
        </div>
    )

    
}
